# General function in pandas

In [2]:
#data manipulations
#dataframe
#melt
import pandas as pd
df = pd.DataFrame({'A':{0:'a',1:'b',2:'c'},'B':{0:1,1:3,2:5},"c":{0:2,1:3,2:4}})
df

A  B  c
0  a  1  2
1  b  3  3
2  c  5  4

In [3]:
pd.melt(df,id_vars=['A'],value_vars=['B'])

A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [4]:
#pivot(index,columns,values)
df = pd.DataFrame({'foo':['one','one','one','two','two','two'],
                  'bar':['A','B','c','A','B','C'],
                  'baz':[1,2,3,4,5,6],
                  'zoo':['x','y','z','q','w','t']})
df

foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   c    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [5]:
df.pivot(index='foo',columns='bar',values='baz')

bar    A    B    C    c
foo                    
one  1.0  2.0  NaN  3.0
two  4.0  5.0  6.0  NaN

In [8]:
#pivot table(values,index,columns)
df=pd.DataFrame({'A':['ni','pi','bi','ki','li'],
                'B':['no','lo','so','po','to'],
                'C':['nu','mu','ju','yu','ru'],
                'D':[1,2,3,4,5],
                'E':[4,5,6,7,8]})
df

A   B   C  D  E
0  ni  no  nu  1  4
1  pi  lo  mu  2  5
2  bi  so  ju  3  6
3  ki  po  yu  4  7
4  li  to  ru  5  8

In [10]:
import numpy as np
table = pd.pivot_table(df,values='D',index=['A','B'],
                      columns=['C'],aggfunc=np.sum)
table

C       ju   mu   nu   ru   yu
A  B                          
bi so  3.0  NaN  NaN  NaN  NaN
ki po  NaN  NaN  NaN  NaN  4.0
li to  NaN  NaN  NaN  5.0  NaN
ni no  NaN  NaN  1.0  NaN  NaN
pi lo  NaN  2.0  NaN  NaN  NaN

In [13]:
#crosstab(index,columns[values,rownames])
#cross tabulation of two factors


a = np.array(["foo","foo","foo","bar","bar"],dtype=object)
b=np.array(["one","one","one","two","one"],dtype=object)
c=np.array(["dull","dull","shiny","dull","dull"],dtype=object)
pd.crosstab(a,[b,c],rownames=['a'],colnames=['b','c'])

b    one        two
c   dull shiny dull
a                  
bar    1     0    1
foo    2     1    0

In [14]:
#cut(x,bins[right,labels,retbins])
#bin values into discrete intervals
pd.cut(np.array([1,7,5,4,6,3]),3)

[(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]]

In [15]:
#qcut(x,q[labels,retbins,precision])
#quantile-based discretization function

pd.qcut(range(5),4)

[(-0.001, 1.0], (-0.001, 1.0], (1.0, 2.0], (2.0, 3.0], (3.0, 4.0]]
Categories (4, interval[float64]): [(-0.001, 1.0] < (1.0, 2.0] < (2.0, 3.0] < (3.0, 4.0]]

In [16]:
#merge(left,right[how,on,left_on])

df1 = pd.DataFrame({'1key':['foo','bar'],'value':[1,2]})

df2 = pd.DataFrame({'ekey':['foo','bar','baz'],'value':[5,6,7]})
df

A   B   C  D  E
0  ni  no  nu  1  4
1  pi  lo  mu  2  5
2  bi  so  ju  3  6
3  ki  po  yu  4  7
4  li  to  ru  5  8

In [17]:
df2

ekey  value
0  foo      5
1  bar      6
2  baz      7

In [18]:
df1

1key  value
0  foo      1
1  bar      2

In [19]:
df1.merge(df2,left_on='1key',right_on='ekey')

1key  value_x ekey  value_y
0  foo        1  foo        5
1  bar        2  bar        6

In [20]:
df1 = pd.DataFrame({'a':['foo','baz'],'b':[1,2]})

df2 = pd.DataFrame({'a':['foo','baz'],'c':[3,4]})

df1

a  b
0  foo  1
1  baz  2

In [21]:
df2

a  c
0  foo  3
1  baz  4

In [22]:
df1.merge(df2,how='inner',on="a")

a  b  c
0  foo  1  3
1  baz  2  4

In [23]:
df1.merge(df2,how='left',on='a')

a  b  c
0  foo  1  3
1  baz  2  4

In [28]:
#merge ordered
#perform merge with optinal filling/interpolation

df1 = pd.DataFrame({
    "key":['a','c','e','a'],
    "lvalue":[1,2,3,1],
    "group":["a","a","a","b"]
})
df1

key  lvalue group
0   a       1     a
1   c       2     a
2   e       3     a
3   a       1     b

In [29]:
df2 = pd.DataFrame({"key":["b","c","d"],"rvalue":[1,2,3]})
df2

key  rvalue
0   b       1
1   c       2
2   d       3

In [30]:
pd.merge_ordered(df1,df2,fill_method="ffill",left_by="group")

key  lvalue group  rvalue
0   a       1     a     NaN
1   b       1     a     1.0
2   c       2     a     2.0
3   d       2     a     3.0
4   e       3     a     3.0
5   a       1     b     NaN
6   b       1     b     1.0
7   c       1     b     2.0
8   d       1     b     3.0

In [31]:
#merge_asof(left,right[on,left_on])
#perform an asof merge

left = pd.DataFrame({"a":[1,5,10],"left_val":['a','b','c']})
left

a left_val
0   1        a
1   5        b
2  10        c

In [32]:
right = pd.DataFrame({"a":[1,2,3,4],"right_val":[1,2,3,6]})
right

a  right_val
0  1          1
1  2          2
2  3          3
3  4          6

In [33]:
pd.merge_asof(left,right,on="a")

a left_val  right_val
0   1        a          1
1   5        b          6
2  10        c          6

In [34]:
pd.merge_asof(left,right,on="a",direction="nearest")


a left_val  right_val
0   1        a          1
1   5        b          6
2  10        c          6

In [35]:
#concat(axis,join,ignire_index)

s1 = pd.Series(['a','b'])
s2= pd.Series(['c','d'])
pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

In [36]:
#get_dummies
#convert categorical variable into dummy/indicator variables

s = pd.Series(list('abcd'))

In [37]:
pd.get_dummies(s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1

In [38]:
#factorize(sort,na_sentinel,size_hint)
#encode the object as an enumerated type or categorical variable

codes, uniques = pd.factorize(['b','b','a','c','b'])
codes

array([0, 0, 1, 2, 0], dtype=int64)

In [40]:
#unique(values)
#hash table-based unique
pd.unique(pd.Series([2,1,3,3]))

array([2, 1, 3], dtype=int64)

In [41]:
#wide to long(df,stubnames,i,j,sep,suffix)
#wide panel to long format
np.random.seed(123)
df=pd.DataFrame({"A1970":{0:"a",1:"b",2:"c"},
                "A1980":{0:"d",1:"e",2:"f"},
                "B1970":{0:2.5,1:1.2,2:.7},
                "B1980":{0:3.2,1:1.3,2:.1},
                "X":dict(zip(range(3),np.random.randn(3)))})
df["id"] = df.index
df

A1970 A1980  B1970  B1980         X  id
0     a     d    2.5    3.2 -1.085631   0
1     b     e    1.2    1.3  0.997345   1
2     c     f    0.7    0.1  0.282978   2

In [42]:
pd.wide_to_long(df,["A","B"],i="id",j="year")

X  A    B
id year                  
0  1970 -1.085631  a  2.5
1  1970  0.997345  b  1.2
2  1970  0.282978  c  0.7
0  1980 -1.085631  d  3.2
1  1980  0.997345  e  1.3
2  1980  0.282978  f  0.1

In [43]:
#insa(obj)
#detect missing values for an array-like object

array = np.array([[1,np.nan,3],[4,5,np.nan]])
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [44]:
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

In [46]:
#isnull(obj)
#detect missing values for an array-like object
df = pd.DataFrame([['ant','bee','cat'],["goat",None,"fly"]])
df

0     1    2
0   ant   bee  cat
1  goat  None  fly

In [47]:
pd.isnull(df)

0      1      2
0  False  False  False
1  False   True  False

In [48]:
#notna(obj)
#Detect non-missing values for an array-like object

array = np.array([[1,np.nan,3],[4,5,np.nan]])
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [49]:
pd.notna(array)

array([[ True, False,  True],
       [ True,  True, False]])

In [52]:
#to_numeric(arg,error,downcast)
#convert argument to a numeric type
a = pd.Series(['1.0','2',-3])
pd.to_numeric(a)

0    1.0
1    2.0
2   -3.0
dtype: float64

In [53]:
pd.to_numeric(a,downcast='float')

0    1.0
1    2.0
2   -3.0
dtype: float32

In [54]:
pd.to_numeric(a,downcast='signed')

0    1
1    2
2   -3
dtype: int8

In [57]:
#to_datetime(arg,error,dayfirst)
#convert argument to datetime

df = pd.DataFrame({"year":[2022,2021],
                  "month":[2,3],
                  "day":[4,5]})
pd.to_datetime(df)

0   2022-02-04
1   2021-03-05
dtype: datetime64[ns]

In [59]:
#to_timedelta(arg,unit,error)
#convert argument to timedelta

pd.to_timedelta('1days 07:05:01.00003')

Timedelta('1 days 07:05:01.000030')

In [60]:
pd.to_timedelta("15.5us")

Timedelta('0 days 00:00:00.000015500')

In [62]:
#data_range(start,end,period,freq,tz)
#return a fixed frequency Datatime index

pd.date_range(start="1/1/2018",end="1/08/2018")

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

In [65]:
#period_range(start,end,periods,freq,name)
#return a fixed frequency period index

pd.period_range(start = "2017-01-01",end="2018-01-01",freq="M")

PeriodIndex(['2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06',
             '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12',
             '2018-01'],
            dtype='period[M]', freq='M')

In [67]:
pd.timedelta_range(start="1 day",periods=4)

TimedeltaIndex(['1 days', '2 days', '3 days', '4 days'], dtype='timedelta64[ns]', freq='D')

In [68]:
#interval_range(start,end,period,freq)
#return a fixed frequency interval index

pd.interval_range(start=0,end=5)

IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]],
              closed='right',
              dtype='interval[int64]')

In [69]:
#interval_range(start,end,periods,freq)
#return a fixed frequency interval index

pd.interval_range(start=0,end=5)

IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]],
              closed='right',
              dtype='interval[int64]')

In [70]:
#eval(expr,parser,engine,truediv)
#evaluate a python expression as a string using various backends

df = pd.DataFrame({"animal":["dog","pig"],"age":[10,20]})
df

animal  age
0    dog   10
1    pig   20

In [71]:
pd.eval("double_age=df.age*2",target=df)

animal  age  double_age
0    dog   10          20
1    pig   20          40

In [72]:
#one-dimensional array
ds = pd.Series([2,4,6,8,10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [74]:
#conversion of pandas module serious to python list

df = pd.Series([4,6,8,10,12])
print("pandas Series and type")
print(df)
#print(type(df))
#print("convert pandas series to python list")
print(df.tolist())
#print(type(df.tolist()))

pandas Series and type
0     4
1     6
2     8
3    10
4    12
dtype: int64
[4, 6, 8, 10, 12]


In [75]:
#pandas Series with add,substract,multiple and divide 

df1 = pd.Series([4,6,8,10,12])

df2 = pd.Series([2,4,6,8,10])

df = df1 +df2
print("add two Series:")
print(df)
print("substract two series:")
df = df1-df2
print(df)
print("Multiple two Series")
df = df1*df2
print(df)
print("divide Series1 by Series2:")
df = df1/df2
print(df)

add two Series:
0     6
1    10
2    14
3    18
4    22
dtype: int64
substract two series:
0    2
1    2
2    2
3    2
4    2
dtype: int64
Multiple two Series
0      8
1     24
2     48
3     80
4    120
dtype: int64
divide Series1 by Series2:
0    2.000000
1    1.500000
2    1.333333
3    1.250000
4    1.200000
dtype: float64


In [76]:
#compair the elements of two pandas series
df1 = pd.Series([2,4,6,8,10])
df1 = pd.Series([1,3,5,7,9])
print("Series1:")
print(df1)
print("Series2:")
print(df2)
print("Compare the elements of the said Series:")
print("Equals:")
print(df1==df2)
print("Greater than:")
print(df1>df2)
print("Less than:")
print(df1<df2)

Series1:
0    1
1    3
2    5
3    7
4    9
dtype: int64
Series2:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4    False
dtype: bool
Greater than:
0    False
1    False
2    False
3    False
4    False
dtype: bool
Less than:
0    True
1    True
2    True
3    True
4    True
dtype: bool


In [77]:
#convert a dictionary to a pandas series

d1 = {'a':100,'b':200,'c':300,'d':400}
print("original dictionary:")
print(d1)
new_series  = pd.Series(d1)
print("converted series:")
print(new_series)

original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400}
converted series:
a    100
b    200
c    300
d    400
dtype: int64


In [78]:
#convert numpy array to a pandas series

array = np.array([10,20,30,40])
print("numpy array:")
print(array)
pandas_series = pd.Series(array)
print("converted pandas series")
print(pandas_series)

numpy array:
[10 20 30 40]
converted pandas series
0    10
1    20
2    30
3    40
dtype: int32


In [80]:
#change the data type of a column or a Series

s1 = pd.Series(['100','200','nidhi','300.12','400'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1,errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2     nidhi
3    300.12
4       400
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [85]:
#pandas program to convert the first column of a DataFrame as a Series

d = {'co1':[1,2,3,4,5],'col2':[4,5,6,7,8],'col3':[7,5,8,9,3]}
df = pd.DataFrame(data=d)
print("original DataFrame")
print(df)
s1 = df.iloc[:,0]
print("\n1st column as a Series:")
print(s1)
print(type(s1))

original DataFrame
   co1  col2  col3
0    1     4     7
1    2     5     5
2    3     6     8
3    4     7     9
4    5     8     3

1st column as a Series:
0    1
1    2
2    3
3    4
4    5
Name: co1, dtype: int64
<class 'pandas.core.series.Series'>
