In [1]:
import numpy as np   

# Various attributes

In [2]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])   
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(array.size)   # ndarray.size returns the number of items in the array

9


In [4]:
print(array.shape)   # ndarray.shape return a tuple consisting of array dimension

(3, 3)


In [5]:
print(array.ndim)   #ndarray.ndim returns the number of array dimensions

2


In [6]:
print(array.itemsize)  #ndarray.itemsize returns the memory size of each element in the array

4


In [8]:
  #split()  
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
array = np.array([2,4,6,8,10])
newarray = np.array_split(array,3)
print(newarray)

[array([2, 4]), array([6, 8]), array([10])]


In [11]:
#join()concatenation of to strings in the sequence
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [12]:
#encode() call str encode element-wise
x = np.array(["aAaAaA", " aA ",'abBABba' ])
print("x:",x)

x: ['aAaAaA' ' aA ' 'abBABba']


In [13]:
e = np.char.encode(x,encoding=" cp037")
e

array([b'\x81\xc1\x81\xc1\x81\xc1', b'@\x81\xc1@',
       b'\x81\x82\xc2\xc1\xc2\x82\x81'], dtype='|S7')

In [14]:
d = np.char.decode(e,encoding='cp037')
d

array(['aAaAaA', ' aA ', 'abBABba'], dtype='<U7')

In [18]:
#numpy.around() value rounded to the desired precision
np.around([5,1.5,.2,.5,3.5,4.5])


array([5., 2., 0., 0., 4., 4.])

In [19]:
#numpy.floor()this function returns the largest integer not greater than the input parameter
a = np.array([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.0])
np.floor(a)


array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [20]:
#numpy.ceil()returns the ceiling of an input value
a = np.array([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [21]:
#numpy.round()round an array to the given number of decimal
np.round(562949955342131.5,3)

562949955342131.5

In [22]:
#numpy.rint()
a = np.array([-1.7,-1.5,-0.5,1.2,1.4,1.7,2.0])
np.rint(a)

array([-2., -2., -0.,  1.,  1.,  2.,  2.])

In [23]:
#numpy.fix() round to nearest integer towards zero
np.fix([2.1,2.9,-2.1,-2.9])


array([ 2.,  2., -2., -2.])

In [24]:
#nimpy.trunc()return the truncted value of the input,element-wise
a = np.array([-1.7,-1.6,-0.3,0.2,1.5,1.3,2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [25]:
#numpy.power()
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [26]:
np.power(x1,3)

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [27]:
#numpy.mod()this function return the remainder of division of the corresponding elements in the input array
np.remainder([4,7],[2,3])

array([0, 1], dtype=int32)

In [28]:
#numpy.real()return the real part of the complex data type argument
a = np.array([1+2j,3+4j,5+6j])
a.real

array([1., 3., 5.])

In [29]:
#np.conj()
np.conjugate(1+2j)

(1-2j)

In [30]:
#numpy.angle()
np.angle([1.0,1.0j,1+1j])


array([0.        , 1.57079633, 0.78539816])

In [31]:
np.angle(1+1j,deg=True)

45.0

In [32]:
a = np.array([1+2j,3+4j,5+6j])
a.imag

array([2., 4., 6.])

In [33]:
#numpy.positive()numerical possitive ,element-wise
x1 = np.array(([1.,-1.]))
np.positive(x1)

array([ 1., -1.])

In [34]:
#numpy.true_divide()
x= np.arange(5)
np.true_divide(x,4)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
#numpy.floor_divide()
np.floor_divide(7,3)

2

In [36]:
np.floor_divide([1.,2.,3.,4.],2.5)

array([0., 0., 1., 1.])

In [37]:
np.float_power(x1,3)

array([ 1., -1.])

In [38]:
#numpy.fmod()return the element-wise remainder of division
np.fmod([-3,-2,-2,-1,2,3],2)


array([-1,  0,  0, -1,  0,  1], dtype=int32)

In [40]:
#numpy.modf()return the fractional and integral parts of an array,element-wise
np.modf([0,3.5])

(array([0. , 0.5]), array([0., 3.]))

In [41]:
np.modf(-0.5)

(-0.5, -0.0)

In [42]:
#numpy.divmod()
np.divmod(np.arange(5),3)

(array([0, 0, 0, 1, 1], dtype=int32), array([0, 1, 2, 0, 1], dtype=int32))

statistical finction

In [43]:
#numpy.amin()
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [44]:
np.amin(a)

0

In [45]:
np.amin(a,axis=0)

array([0, 1])

In [47]:
#numpy.ptp()function returns the range(max-min)
x = np.array([[4,9,2,10],
            [6,9,7,12]])

In [48]:
np.ptp(x,axis=1)

array([8, 6])

In [49]:
#numpy.percentile()use to measure the statistical indication 
a = np.array([[10,7,4],[3,2,1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [50]:
np.percentile(a,50)

3.5

In [51]:
#numpy.median()separating the hogher half of a data sample from the lower half
a = np.array([[20,9,6],[3,4,5]])
a

array([[20,  9,  6],
       [ 3,  4,  5]])

In [52]:
np.median(a,axis=0)

array([11.5,  6.5,  5.5])

In [53]:
#numpy.mean()function return the arithmetic mean of element
a = np.array([[1,2],[3,4]])
np.mean(a)

2.5

In [54]:
#numpy.average()
data= np.arange(1,5)
data


array([1, 2, 3, 4])

In [55]:
np.average(data)

2.5

In [57]:
np.average(np.arange(1,11), weights = np.arange(10,0,-1))

4.0

In [61]:
#np.sort( function returns a sorted copy of the input array)
a = np.array([[1,4],[3,1]])  #sort along last axis
np.sort(a)

array([[1, 4],
       [1, 3]])

In [62]:
np.sort(a,axis=0)   #sort along first axis

array([[1, 1],
       [3, 4]])

In [64]:
np.sort(a,axis=None)   #sort flattened array


array([1, 1, 3, 4])

In [65]:
#numpy.where()input array where the given condition is satisfied
a = np.random.randn(2,3)
print(a)

[[-0.24483577 -0.46904396 -1.08863684]
 [ 0.56977822 -0.01401374 -0.55651819]]


In [66]:
b = np.where(a>0,a,0)
b

array([[0.        , 0.        , 0.        ],
       [0.56977822, 0.        , 0.        ]])

In [67]:
cond= np.mod(arr,3)==0
cond

array([False, False,  True, False, False,  True])

In [69]:
np.extract(cond,arr)

array([3, 6])

In [70]:
#numpy.sum()
np.sum([[0,1],[0,5]])

6

In [71]:
np.sum([[0,1],[0,5]],axis=0)

array([0, 6])

In [72]:
#numpy.diff()
x=np.array([1,2,4,7,0])
np.diff(x)

array([ 1,  2,  3, -7])

In [73]:
#numpy.ediff1d() differences between consecutive element of an array
x=np.array([1,2,4,7,0])
np.ediff1d(x)

array([ 1,  2,  3, -7])

In [74]:
y = [[1,2,4],[1,6,24]]
np.ediff1d(y)

array([ 1,  2, -3,  5, 18])

In [75]:
#return the cross product of two array
x=[1,2,3]
y=[5,6,7]
np.cross(x,y)

array([-4,  8, -4])

In [76]:
#numpy.gradient()return the gradient of an N-dimensional array
f =np.array([1,2,4,7,11,16],dtype=float)
np.gradient(f)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [77]:
np.gradient(f,2)

array([0.5 , 0.75, 1.25, 1.75, 2.25, 2.5 ])