In [1]:
import numpy as np   # importing the numpy


In [2]:
array = np.arange(10)    # arange function
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
array = np.arange(10,30)   # arange with 10 t0 30
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [10]:
myarray = np.arange(20)
myarray= myarray.reshape(4,5)
print(myarray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
myarray = myarray.reshape(10,2)
print(myarray)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [18]:
print(myarray.shape)

(10, 2)


In [19]:
print(myarray.ndim)

2


In [20]:
print(myarray.size)

20


In [21]:
array = np.arange(10)
array=array.reshape(5,2)
print(array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
print(array.shape)

(5, 2)


In [23]:
print(array.size)

10


In [24]:
print(array.ndim)

2


In [25]:
print(array.dtype)

int32


In [26]:
array = np.zeros((3,4))  # array with zero
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
array = np.ones((2,4))   # ones creats an array with all ones
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
array = np.random.rand(3,4)
print(array)    #numpy random module helps to initialize array with random values

[[0.86087887 0.41543833 0.33611068 0.94396768]
 [0.33636643 0.19065704 0.79430734 0.75625926]
 [0.66216695 0.99415474 0.07193481 0.25985445]]
