In [68]:
array = np.arange(0,30,2)
print(array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [70]:
my=array.reshape(5,3)
print(my)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


In [72]:
print(array.flat[5]) #returns an 1-5 iterator

10


In [75]:
print(my.flatten())   #restore the reshaped array

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [77]:
print(my.transpose())  # thos helps to transposr of the given array

[[ 0  6 12 18 24]
 [ 2  8 14 20 26]
 [ 4 10 16 22 28]]


In [79]:
myarray= np.arange(8).reshape(2,2,2)   # interchange the two axes of an array
print(myarray)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [80]:
print(np.swapaxes(myarray,2,0))

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [81]:
print(np.rollaxis(myarray,2))

[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [82]:
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [83]:
print(np.resize(array,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [84]:
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [85]:
print(np.append(array,[7,8,9]))

[1 2 3 4 5 6 7 8 9]


# numpy mathmetical function

In [86]:
angles = np.array([0,30,45,60,90,180,360])
print(angles)

[  0  30  45  60  90 180 360]


In [88]:
print(np.sin(angles*np.pi/180))   #convert to radians by multiplying with pi/180

[ 0.00000000e+00  5.00000000e-01  7.07106781e-01  8.66025404e-01
  1.00000000e+00  1.22464680e-16 -2.44929360e-16]


In [90]:
 print(np.cos(angles*np.pi/180))    #for cosine of angles

[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00  1.00000000e+00]


In [92]:
print(np.tan(angles*np.pi/180))   #for getting cosine of angles

[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.22464680e-16 -2.44929360e-16]


In [96]:
sine = np.sin(angles * np.pi/180)
sineinv =  np.arcsin(sine)           #for computing inverse of trigonometric functions

In [98]:
print(np.degrees(sineinv))       #computing angle from inverse

[ 0.00000000e+00  3.00000000e+01  4.50000000e+01  6.00000000e+01
  9.00000000e+01  7.01670930e-15 -1.40334186e-14]


In [100]:
print(np.around(sine,4))    #for rounding the values

[ 0.      0.5     0.7071  0.866   1.      0.     -0.    ]


In [101]:
print(np.floor(sine))  #for rounding to previous integer

[ 0.  0.  0.  0.  1.  0. -1.]


In [102]:
#for rounding to text integer
print(np.ceil(sine))

[ 0.  1.  1.  1.  1.  1. -0.]


In [103]:
myarray = np.arange(12).reshape(3,4)
print(myarray)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [104]:
array=np.arange(4)
print(array)

[0 1 2 3]


In [106]:
print(np.subtract(myarray,array))   # subtracting above two arrays

[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


In [107]:
print(np.add(myarray,array))   #adding above two array

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [109]:
print(np.multiply(array,myarray))   # multiplication of two array

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]


In [111]:
print(np.divide(array,myarray))    #division of two array

[[       nan 1.         1.         1.        ]
 [0.         0.2        0.33333333 0.42857143]
 [0.         0.11111111 0.2        0.27272727]]


<ipython-input-111-85307c1b1c1b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(array,myarray))    #division of two array


In [114]:
#numpy.power():   return array element raised to the specified value result
array = np.array([1,2,3])
print(np.power(array,2))

[1 4 9]
